/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.proyect.db;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Angelius
 */
public class ConsultCourse extends javax.swing.JFrame {

    /**
     * Creates new form ConsultProfessor
     */
    public ConsultCourse()  {
        initComponents();
        try {
            
            showCourses();
            
        } catch (Exception ex) {
            Logger.getLogger(ConsultCourse.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        jTextFieldSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Courses");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 27, -1, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, 1005, 230));

        jButton1.setText("Operations Items");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, -1, -1));

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, -1, -1));
        jPanel1.add(jTextFieldSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 162, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        ConsultCourseOperationItems buttonCourseOperationItems = new ConsultCourseOperationItems();
        buttonCourseOperationItems.setVisible(true);

        ConsultCourseOperationItems.jLabel1.setVisible(false);
        ConsultCourseOperationItems.jLabel2.setVisible(false);
        ConsultCourseOperationItems.jLabel3.setVisible(false);
        ConsultCourseOperationItems.jLabel13Professor.setVisible(false);
        ConsultCourseOperationItems.jButton4ApplyDeleteItem.setVisible(false);
        ConsultCourseOperationItems.jButton4ApplyModifyItem.setVisible(false);
        ConsultCourseOperationItems.jLabel4AddItem.setVisible(false);
        ConsultCourseOperationItems.jLabel4DeleteItem.setVisible(false);
        ConsultCourseOperationItems.jLabel5ModifyItem.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed

        /*
        try {
            showProfessorSearch();

            String field = jTextFieldSearch.getText();
            String where = "";

            if(!"".equals(field)){
                where = "IDProfessor, NameT, Times from professor where IDProfessor like '%" + field +
                "%' or NameT like '%" + field + "%' or Times like '%" + field +"%'";
            }

            try{
                DefaultTableModel modelo0 = new DefaultTableModel();
                tabla.setModel(modelo0);

                PreparedStatement ps = null;
                ResultSet rs = null;

                Connection conn = null;

                String sql = "SELECT " + where;
                ps = conn.prepareStatement(sql);
                rs = ps.executeQuery();

                ResultSetMetaData rsMd = rs.getMetaData();
                int CantityColumns = rsMd.getColumnCount();

                modelo0.addColumn("IDProfessor");
                modelo0.addColumn("NameT");
                modelo0.addColumn("Times");

                while(rs.next()){

                    Object[] rows = new Object[CantityColumns];

                    for(int i = 0; i < CantityColumns; i++){
                        rows[i] = rs.getObject(i + 1);
                    }
                    modelo0.addRow(rows);
                }

            } catch (SQLException ex) {
                Logger.getLogger(ConsultProfessor.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (Exception ex) {
            Logger.getLogger(ConsultProfessor.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_SearchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ConsultCourse().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ConsultCourse.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    

        public void showCourses() throws Exception
    {
        InterfaceFinalProjectDB logicaC = new InterfaceFinalProjectDB();
        
        DefaultTableModel modelo = logicaC.showCourses();
        
        tabla.setModel(modelo);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton SearchButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
