/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.proyect.db;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angelius
 */
public class ConsultProfessorOperationItems extends javax.swing.JFrame {

    /**
     * Creates new form ConsultRoomOperationItems
     */
    public ConsultProfessorOperationItems() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField1ProfessorID = new javax.swing.JTextField();
        jTextField2ProfessorName = new javax.swing.JTextField();
        jTextField3ProfessorTime = new javax.swing.JTextField();
        jLabel4AddItem = new javax.swing.JLabel();
        jLabel4DeleteItem = new javax.swing.JLabel();
        jLabel5ModifyItem = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2ModifyProfessorID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField3ModifyProfessorName = new javax.swing.JTextField();
        jTextField4ModifyProfessorTime = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField5ModifyProfessorIDDone = new javax.swing.JTextField();
        jTextField6ModifyProfessorNameDone = new javax.swing.JTextField();
        jTextField7ModifyProfessorTimeDone = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4ApplyAddItem = new javax.swing.JButton();
        jButton5Cancel = new javax.swing.JButton();
        jButton4ApplyDeleteItem = new javax.swing.JButton();
        jButton4ApplyModifyItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 440, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Professor ID:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 31));

        jLabel2.setText("Professor Name::");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 90, 25));

        jLabel3.setText("Professor Time ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 22));

        jLabel13.setText("(FullTime, Partial Time):");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, -1));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Please select an operation");
        jTextField1.setBorder(null);
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 420, 170));
        jPanel2.add(jTextField1ProfessorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 193, -1));

        jTextField2ProfessorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ProfessorNameActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2ProfessorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 193, -1));
        jPanel2.add(jTextField3ProfessorTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 193, -1));

        jLabel4AddItem.setText("Add Item");
        jPanel2.add(jLabel4AddItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 104, -1));

        jLabel4DeleteItem.setText("Delete Item");
        jPanel2.add(jLabel4DeleteItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 104, -1));

        jLabel5ModifyItem.setText("Modify Item");
        jPanel2.add(jLabel5ModifyItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 104, -1));

        jButton4.setText("Delete all in table");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Professor ID:");

        jLabel5.setText("Professor Name:");

        jLabel6.setText("Professor Time:");

        jLabel7.setText("Original Data");

        jLabel8.setText("Modify");

        jLabel9.setText("------------------>");

        jLabel10.setText("Professor ID:");

        jLabel11.setText("Professor Name:");

        jLabel12.setText("Professor Time:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(45, 45, 45)
                .addComponent(jLabel8)
                .addGap(96, 96, 96))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField3ModifyProfessorName)
                    .addComponent(jTextField4ModifyProfessorTime)
                    .addComponent(jTextField2ModifyProfessorID, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jTextField5ModifyProfessorIDDone, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField7ModifyProfessorTimeDone)
                            .addComponent(jTextField6ModifyProfessorNameDone, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField2ModifyProfessorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField3ModifyProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField4ModifyProfessorTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField5ModifyProfessorIDDone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField6ModifyProfessorNameDone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField7ModifyProfessorTimeDone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel4);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 68, 420, 260));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton1.setText("Add Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 27, 102, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton2.setText("Delete Item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 100, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton3.setText("Modify Item");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 100, -1));

        jButton4ApplyAddItem.setBackground(new java.awt.Color(51, 153, 255));
        jButton4ApplyAddItem.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton4ApplyAddItem.setText("Apply");
        jButton4ApplyAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ApplyAddItemActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4ApplyAddItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 100, -1));

        jButton5Cancel.setBackground(new java.awt.Color(204, 0, 102));
        jButton5Cancel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton5Cancel.setText("Cancel");
        jButton5Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5CancelActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 100, -1));

        jButton4ApplyDeleteItem.setBackground(new java.awt.Color(51, 153, 255));
        jButton4ApplyDeleteItem.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton4ApplyDeleteItem.setText("Apply");
        jButton4ApplyDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ApplyDeleteItemActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4ApplyDeleteItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 100, -1));

        jButton4ApplyModifyItem.setBackground(new java.awt.Color(51, 153, 255));
        jButton4ApplyModifyItem.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton4ApplyModifyItem.setText("Apply");
        jButton4ApplyModifyItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ApplyModifyItemActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4ApplyModifyItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        jButton4.setVisible(false);
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        jLabel13.setVisible(true);
        jTextField1.setVisible(false);
        jTextField2ProfessorName.setVisible(true);
        jTextField3ProfessorTime.setVisible(true);
        jButton4ApplyAddItem.setVisible(true);
        jButton4ApplyModifyItem.setVisible(false);
        jButton4ApplyDeleteItem.setVisible(false);
        ConsultProfessorOperationItems.jLabel4AddItem.setVisible(true);
        ConsultProfessorOperationItems.jLabel4DeleteItem.setVisible(false);
        ConsultProfessorOperationItems.jLabel5ModifyItem.setVisible(false);
        
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel13.setVisible(false);
        jTextField2ProfessorName.setVisible(false);
        jTextField3ProfessorTime.setVisible(false);
        jButton4.setVisible(true);
        jLabel1.setVisible(true);
        jTextField1.setVisible(false);
        ConsultProfessorOperationItems.jLabel4DeleteItem.setVisible(true);
        ConsultProfessorOperationItems.jLabel4AddItem.setVisible(false);
        ConsultProfessorOperationItems.jLabel5ModifyItem.setVisible(false);
        jButton4ApplyAddItem.setVisible(false);
        jButton4ApplyModifyItem.setVisible(false);
        jButton4ApplyDeleteItem.setVisible(true);
        
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        jButton4.setVisible(false);
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        jLabel13.setVisible(false);
        jTextField1.setVisible(false);
        ConsultProfessorOperationItems.jLabel5ModifyItem.setVisible(true);
        ConsultProfessorOperationItems.jLabel4AddItem.setVisible(false);
        ConsultProfessorOperationItems.jLabel4DeleteItem.setVisible(false);
        jButton4ApplyAddItem.setVisible(false);
        jButton4ApplyDeleteItem.setVisible(false);
        jButton4ApplyModifyItem.setVisible(true);
        
       jTabbedPane1.setSelectedIndex(1);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ApplyAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ApplyAddItemActionPerformed
        
        jButton4ApplyDeleteItem.setVisible(false);
        jButton4ApplyModifyItem.setVisible(false);
        
        DefaultTableModel modelo = new DefaultTableModel();

            PreparedStatement ps = null;
            try{
                Conexion objCon = new Conexion();
                Connection conn = objCon.getConection();
                ps = conn.prepareStatement("INSERT INTO `practicedb`.`professor` (`IDProfessor`, `NameT`, `Times`) VALUES (?, ?, ?);");
                ps.setString(1, jTextField1ProfessorID.getText());
                ps.setString(2, jTextField2ProfessorName.getText());
                ps.setString(3, jTextField3ProfessorTime.getText());
                                
                ps.execute();
                
                JOptionPane.showMessageDialog(null, "Item added succesfully");
                Object[] fila = new Object[3];
                fila[0] = jTextField1ProfessorID.getText();
                fila[1] = jTextField2ProfessorName.getText();
                fila[2] = jTextField3ProfessorTime.getText();
                modelo.addRow(fila);
            }   catch (SQLException ex) {
                Logger.getLogger(InterfaceFinalProjectDB.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_jButton4ApplyAddItemActionPerformed

    private void jButton4ApplyDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ApplyDeleteItemActionPerformed
        
        
        jButton4ApplyAddItem.setVisible(false);
        jButton4ApplyModifyItem.setVisible(false);
                DefaultTableModel modelo = new DefaultTableModel();

            PreparedStatement ps = null;
            try{
                Conexion objCon = new Conexion();
                Connection conn = objCon.getConection();
                ps = conn.prepareStatement("DELETE FROM `practicedb`.`room` WHERE (`RoomId` = ?);");
                ps.setString(1, jTextField1ProfessorID.getText());
                
                
                ps.execute();
                
                JOptionPane.showMessageDialog(null, "Item deleted succesfully");
                Object[] fila = new Object[1];
                fila[0] = jTextField1ProfessorID.getText();
                
                modelo.addRow(fila);
            }   catch (SQLException ex) {
                Logger.getLogger(InterfaceFinalProjectDB.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_jButton4ApplyDeleteItemActionPerformed

    private void jButton4ApplyModifyItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ApplyModifyItemActionPerformed
        
              
       DefaultTableModel modelo = new DefaultTableModel();
       
       String ProfessorIDText = jTextField5ModifyProfessorIDDone.getText();
       String ProfessorNameText = jTextField6ModifyProfessorNameDone.getText();
       String ProfessorTimeText = jTextField7ModifyProfessorTimeDone.getText();
              
            PreparedStatement ps = null;
            try{
                Conexion objCon = new Conexion();
                Connection conn = objCon.getConection();
                ps = conn.prepareStatement("UPDATE `practicedb`.`professor` SET `IDProfessor` = '"+ProfessorIDText+"', `NameT` = '"+ProfessorNameText+
                        "', `Times` = '"+ProfessorTimeText+"' WHERE (`IDProfessor` = ?);");
                ps.setString(1, jTextField2ModifyProfessorID.getText());

                
                ps.execute();
                
                JOptionPane.showMessageDialog(null, "Item modified succesfully");
                Object[] fila = new Object[3];
                fila[0] = jTextField5ModifyProfessorIDDone.getText();
                fila[1] = jTextField6ModifyProfessorNameDone.getText();
                fila[2] = jTextField7ModifyProfessorTimeDone.getText();
                modelo.addRow(fila);
            }   catch (SQLException ex) {
                Logger.getLogger(InterfaceFinalProjectDB.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton4ApplyModifyItemActionPerformed

    private void jButton5CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5CancelActionPerformed
        try {
            Conexion.getConection().rollback();
        } catch (SQLException ex) {
            Logger.getLogger(ConsultCourseOperationItems.class.getName()).log(Level.SEVERE, null, ex);
        }       
    }//GEN-LAST:event_jButton5CancelActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     
          
       int confirmado = JOptionPane.showConfirmDialog(null,
                        "Are you sure you want drop this table?");

    if (JOptionPane.OK_OPTION == confirmado){
        System.out.println("Table dropped");
        
         DefaultTableModel modelo = new DefaultTableModel();
            PreparedStatement ps = null;
            try{
                Conexion objCon = new Conexion();
                Connection conn = objCon.getConection();
                ps = conn.prepareStatement("DROP TABLE Professor;");
                ps.setString(1, jTextField2ModifyProfessorID.getText());
                
                
                ps.execute();
                
                JOptionPane.showMessageDialog(null, "Table dropped");
                Object[] fila = new Object[3];
                fila[0] = null;
                fila[1] = null;
                fila[2] = null;
                modelo.addRow(fila);
            }   catch (SQLException ex) {
                Logger.getLogger(InterfaceFinalProjectDB.class.getName()).log(Level.SEVERE, null, ex);
            }
            
    }else{
            System.out.println("No table dropped");
    }
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField2ProfessorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ProfessorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ProfessorNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultProfessorOperationItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultProfessorOperationItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultProfessorOperationItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultProfessorOperationItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultProfessorOperationItems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public static javax.swing.JButton jButton4;
    private javax.swing.JButton jButton4ApplyAddItem;
    public static javax.swing.JButton jButton4ApplyDeleteItem;
    public static javax.swing.JButton jButton4ApplyModifyItem;
    private javax.swing.JButton jButton5Cancel;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel4AddItem;
    public static javax.swing.JLabel jLabel4DeleteItem;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel5ModifyItem;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField1ProfessorID;
    private javax.swing.JTextField jTextField2ModifyProfessorID;
    private javax.swing.JTextField jTextField2ProfessorName;
    private javax.swing.JTextField jTextField3ModifyProfessorName;
    private javax.swing.JTextField jTextField3ProfessorTime;
    private javax.swing.JTextField jTextField4ModifyProfessorTime;
    private javax.swing.JTextField jTextField5ModifyProfessorIDDone;
    private javax.swing.JTextField jTextField6ModifyProfessorNameDone;
    private javax.swing.JTextField jTextField7ModifyProfessorTimeDone;
    // End of variables declaration//GEN-END:variables
}
