/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.proyect.db;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angelius
 */
public class ConsultReservationOperationItems extends javax.swing.JFrame {

    /**
     * Creates new form ConsultRoomOperationItems
     */
    public ConsultReservationOperationItems() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1RoomID = new javax.swing.JTextField();
        jTextField3DateTime = new javax.swing.JTextField();
        jLabel4DeleteItem = new javax.swing.JLabel();
        jLabel5ModifyItem = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2ModifyRoomID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField3ModifyName = new javax.swing.JTextField();
        jTextField4ModifyDateAndTime = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField5ModifyRoomIDDone = new javax.swing.JTextField();
        jTextField6ModifyNameDone = new javax.swing.JTextField();
        jTextField7ModifyDateAndTimeDone = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField8ModifyDuration = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField9ModifyDurationDone = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5Cancel = new javax.swing.JButton();
        jButton4ApplyDeleteItem = new javax.swing.JButton();
        jButton4ApplyModifyItem = new javax.swing.JButton();

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Please select an operation");
        jTextField1.setBorder(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 440, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Room ID:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 90, 31));

        jLabel3.setText("Date and Time:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 22));
        jPanel2.add(jTextField1RoomID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 193, -1));
        jPanel2.add(jTextField3DateTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 193, -1));

        jLabel4DeleteItem.setText("Delete Item");
        jPanel2.add(jLabel4DeleteItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 104, -1));

        jLabel5ModifyItem.setText("Modify Item");
        jPanel2.add(jLabel5ModifyItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 104, -1));

        jButton4.setText("Delete all in table");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Room ID:");

        jLabel5.setText("Your Name");

        jLabel6.setText("Date and Time");

        jLabel7.setText("Original Data");

        jLabel8.setText("Modify");

        jLabel9.setText("------------------>");

        jLabel10.setText("Room ID:");

        jLabel11.setText("Your Name:");

        jLabel12.setText("Date and Time:");

        jLabel13.setText("Duration:");

        jLabel14.setText("Duration:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(45, 45, 45)
                .addComponent(jLabel8)
                .addGap(96, 96, 96))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addComponent(jLabel13))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField4ModifyDateAndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(37, 37, 37)
                                .addComponent(jTextField9ModifyDurationDone, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField6ModifyNameDone, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField5ModifyRoomIDDone, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField7ModifyDateAndTimeDone, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(43, 43, 43))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3ModifyName)
                            .addComponent(jTextField2ModifyRoomID, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(jTextField8ModifyDuration))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2ModifyRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField5ModifyRoomIDDone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3ModifyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField6ModifyNameDone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12)
                            .addComponent(jTextField7ModifyDateAndTimeDone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField4ModifyDateAndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField8ModifyDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(jTextField9ModifyDurationDone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("tab2", jPanel4);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 68, 420, 260));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton2.setText("Delete Item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 100, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton3.setText("Modify Item");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 100, -1));

        jButton5Cancel.setBackground(new java.awt.Color(204, 0, 102));
        jButton5Cancel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton5Cancel.setText("Cancel");
        jButton5Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5CancelActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 100, -1));

        jButton4ApplyDeleteItem.setBackground(new java.awt.Color(51, 153, 255));
        jButton4ApplyDeleteItem.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton4ApplyDeleteItem.setText("Apply");
        jButton4ApplyDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ApplyDeleteItemActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4ApplyDeleteItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 100, -1));

        jButton4ApplyModifyItem.setBackground(new java.awt.Color(51, 153, 255));
        jButton4ApplyModifyItem.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton4ApplyModifyItem.setText("Apply");
        jButton4ApplyModifyItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ApplyModifyItemActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4ApplyModifyItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        jLabel3.setVisible(true);
        jTextField3DateTime.setVisible(true);
        jButton4.setVisible(true);
        jLabel1.setVisible(true);
        jTextField1.setVisible(false);
        ConsultReservationOperationItems.jLabel4DeleteItem.setVisible(true);
        ConsultReservationOperationItems.jLabel5ModifyItem.setVisible(false);
        jButton4ApplyModifyItem.setVisible(false);
        jButton4ApplyDeleteItem.setVisible(true);
        
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        jButton4.setVisible(false);
        jLabel1.setVisible(true);
        jLabel3.setVisible(true);
        jTextField1.setVisible(false);
        ConsultReservationOperationItems.jLabel5ModifyItem.setVisible(true);
                ConsultReservationOperationItems.jLabel4DeleteItem.setVisible(false);
                jButton4ApplyDeleteItem.setVisible(false);
        jButton4ApplyModifyItem.setVisible(true);
        
       jTabbedPane1.setSelectedIndex(1);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ApplyDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ApplyDeleteItemActionPerformed
        
        
        
        jButton4ApplyModifyItem.setVisible(false);
        DefaultTableModel modelo = new DefaultTableModel();

            PreparedStatement ps = null;
            try{
                Conexion objCon = new Conexion();
                Connection conn = objCon.getConection();
                ps = conn.prepareStatement("DELETE FROM `practicedb`.`RESERVATION` WHERE (`RoomId` = ?) and (`DateTimeT` = ?);");
                ps.setString(1, jTextField1RoomID.getText());
                ps.setString(2, jTextField3DateTime.getText());                
                
                ps.execute();
                
                JOptionPane.showMessageDialog(null, "Item deleted succesfully");
                Object[] fila = new Object[2];
                fila[0] = jTextField1RoomID.getText();
                fila[1] = jTextField3DateTime.getText();                
                
                modelo.addRow(fila);
            }   catch (SQLException ex) {
                Logger.getLogger(InterfaceFinalProjectDB.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_jButton4ApplyDeleteItemActionPerformed

    private void jButton4ApplyModifyItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ApplyModifyItemActionPerformed
        
              
       DefaultTableModel modelo = new DefaultTableModel();
       
       String RRoomIDText = jTextField5ModifyRoomIDDone.getText();
       String RNameText = jTextField6ModifyNameDone.getText();
       String RTimeText = jTextField7ModifyDateAndTimeDone.getText();
       String RDurationText =jTextField9ModifyDurationDone.getText();
       
            PreparedStatement ps = null;
            try{
                Conexion objCon = new Conexion();
                Connection conn = objCon.getConection();
                ps = conn.prepareStatement("UPDATE `practicedb`.`RESERVATION` SET `RoomId` = '"+RRoomIDText+"', `NameTT` = '"+RNameText
                        +"', `DateTimeT` = '"+RTimeText+"', `Duration` = '"+RDurationText+"' "
                        + "WHERE (`RoomId` = ?) and (`DateTimeT` = ?);");
                ps.setString(1, jTextField2ModifyRoomID.getText());
                ps.setString(2, jTextField3ModifyName.getText());
                
                
                ps.execute();
                
                JOptionPane.showMessageDialog(null, "Item modified succesfully");
                Object[] fila = new Object[4];
                fila[0] = jTextField5ModifyRoomIDDone.getText();
                fila[1] = jTextField6ModifyNameDone.getText();
                fila[2] = jTextField7ModifyDateAndTimeDone.getText();
                fila[3] = jTextField9ModifyDurationDone.getText();
                modelo.addRow(fila);
            }   catch (SQLException ex) {
                Logger.getLogger(InterfaceFinalProjectDB.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton4ApplyModifyItemActionPerformed

    private void jButton5CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5CancelActionPerformed
        try {
            Conexion.getConection().rollback();
        } catch (SQLException ex) {
            Logger.getLogger(ConsultCourseOperationItems.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5CancelActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     
          
       int confirmado = JOptionPane.showConfirmDialog(null,
                        "Are you sure you want drop this table?");

    if (JOptionPane.OK_OPTION == confirmado){
        System.out.println("Table dropped");
        
         DefaultTableModel modelo = new DefaultTableModel();
            PreparedStatement ps = null;
            try{
                Conexion objCon = new Conexion();
                Connection conn = objCon.getConection();
                ps = conn.prepareStatement("DROP TABLE reservation;");
                ps.setString(1, jTextField2ModifyRoomID.getText());
                
                
                ps.execute();
                
                JOptionPane.showMessageDialog(null, "Table dropped");
                Object[] fila = new Object[3];
                fila[0] = null;
                fila[1] = null;
                fila[2] = null;
                modelo.addRow(fila);
            }   catch (SQLException ex) {
                Logger.getLogger(InterfaceFinalProjectDB.class.getName()).log(Level.SEVERE, null, ex);
            }
            
    }else{
            System.out.println("No table dropped");
    }
       
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultReservationOperationItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultReservationOperationItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultReservationOperationItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultReservationOperationItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultReservationOperationItems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public static javax.swing.JButton jButton4;
    public static javax.swing.JButton jButton4ApplyDeleteItem;
    public static javax.swing.JButton jButton4ApplyModifyItem;
    private javax.swing.JButton jButton5Cancel;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel4DeleteItem;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel5ModifyItem;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField1RoomID;
    private javax.swing.JTextField jTextField2ModifyRoomID;
    public static javax.swing.JTextField jTextField3DateTime;
    private javax.swing.JTextField jTextField3ModifyName;
    private javax.swing.JTextField jTextField4ModifyDateAndTime;
    private javax.swing.JTextField jTextField5ModifyRoomIDDone;
    private javax.swing.JTextField jTextField6ModifyNameDone;
    private javax.swing.JTextField jTextField7ModifyDateAndTimeDone;
    private javax.swing.JTextField jTextField8ModifyDuration;
    private javax.swing.JTextField jTextField9ModifyDurationDone;
    // End of variables declaration//GEN-END:variables
}
