/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.proyect.db;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angelius
 */
public class ConsultCourseOperationItems extends javax.swing.JFrame {

    /**
     * Creates new form ConsultRoomOperationItems
     */
    public ConsultCourseOperationItems() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13Professor = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField1CourseCode = new javax.swing.JTextField();
        jTextField2Section = new javax.swing.JTextField();
        jTextField3Title = new javax.swing.JTextField();
        jTextField8Professor = new javax.swing.JTextField();
        jLabel4AddItem = new javax.swing.JLabel();
        jLabel4DeleteItem = new javax.swing.JLabel();
        jLabel5ModifyItem = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2ModifyCourseCode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField3ModifySection = new javax.swing.JTextField();
        jTextField4ModifyTitle = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField5ModifyCourseCodeDone = new javax.swing.JTextField();
        jTextField6ModifySectionDone = new javax.swing.JTextField();
        jTextField7ModifyTitleDone = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField8ModifyProfessor = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField9ModifyProfessorDone = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4ApplyAddItem = new javax.swing.JButton();
        jButton5Cancel = new javax.swing.JButton();
        jButton4ApplyDeleteItem = new javax.swing.JButton();
        jButton4ApplyModifyItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 440, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Course Code:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 49, 90, 31));

        jLabel2.setText("Section:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 55, 25));

        jLabel3.setText("Tittle:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 22));

        jLabel13Professor.setText("Professor:");
        jPanel2.add(jLabel13Professor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Please select an operation");
        jTextField1.setBorder(null);
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 420, 170));
        jPanel2.add(jTextField1CourseCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 54, 193, -1));

        jTextField2Section.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2SectionActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2Section, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 193, -1));
        jPanel2.add(jTextField3Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 193, -1));
        jPanel2.add(jTextField8Professor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 190, -1));

        jLabel4AddItem.setText("Add Item");
        jPanel2.add(jLabel4AddItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 104, -1));

        jLabel4DeleteItem.setText("Delete Item");
        jPanel2.add(jLabel4DeleteItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 104, -1));

        jLabel5ModifyItem.setText("Modify Item");
        jPanel2.add(jLabel5ModifyItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 104, -1));

        jButton4.setText("Delete all in table");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Course Code:");

        jLabel5.setText("Section:");

        jLabel6.setText("Title:");

        jLabel7.setText("Original Data");

        jLabel8.setText("Modify");

        jLabel9.setText("------------------>");

        jLabel10.setText("Course Code:");

        jLabel11.setText("Section:");

        jLabel12.setText("Tittle:");

        jLabel13.setText("Professor:");

        jLabel14.setText("Professor:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(45, 45, 45)
                .addComponent(jLabel8)
                .addGap(96, 96, 96))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField3ModifySection)
                    .addComponent(jTextField4ModifyTitle)
                    .addComponent(jTextField2ModifyCourseCode, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(jTextField8ModifyProfessor))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField9ModifyProfessorDone))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField7ModifyTitleDone, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(jTextField6ModifySectionDone)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField5ModifyCourseCodeDone, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2ModifyCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField5ModifyCourseCodeDone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3ModifySection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField6ModifySectionDone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4ModifyTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField7ModifyTitleDone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField8ModifyProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(jTextField9ModifyProfessorDone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("tab2", jPanel4);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 68, 420, 260));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton1.setText("Add Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 27, 102, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton2.setText("Delete Item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 100, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton3.setText("Modify Item");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 100, -1));

        jButton4ApplyAddItem.setBackground(new java.awt.Color(51, 153, 255));
        jButton4ApplyAddItem.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton4ApplyAddItem.setText("Apply");
        jButton4ApplyAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ApplyAddItemActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4ApplyAddItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 100, -1));

        jButton5Cancel.setBackground(new java.awt.Color(204, 0, 102));
        jButton5Cancel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton5Cancel.setText("Cancel");
        jButton5Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5CancelActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 100, -1));

        jButton4ApplyDeleteItem.setBackground(new java.awt.Color(51, 153, 255));
        jButton4ApplyDeleteItem.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton4ApplyDeleteItem.setText("Apply");
        jButton4ApplyDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ApplyDeleteItemActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4ApplyDeleteItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 100, -1));

        jButton4ApplyModifyItem.setBackground(new java.awt.Color(51, 153, 255));
        jButton4ApplyModifyItem.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton4ApplyModifyItem.setText("Apply");
        jButton4ApplyModifyItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ApplyModifyItemActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4ApplyModifyItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        jButton4.setVisible(false);
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        jLabel13Professor.setVisible(true);
        jTextField1.setVisible(false);
        jTextField2Section.setVisible(true);
        jTextField3Title.setVisible(true);
        jTextField8Professor.setVisible(true);
        jButton4ApplyAddItem.setVisible(true);
        jButton4ApplyModifyItem.setVisible(false);
        jButton4ApplyDeleteItem.setVisible(false);
        ConsultCourseOperationItems.jLabel4AddItem.setVisible(true);
        ConsultCourseOperationItems.jLabel4DeleteItem.setVisible(false);
        ConsultCourseOperationItems.jLabel5ModifyItem.setVisible(false);
        
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        jLabel13Professor.setVisible(false);        
        jTextField8Professor.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jTextField2Section.setVisible(false);
        jTextField3Title.setVisible(false);
        jButton4.setVisible(true);
        jLabel1.setVisible(true);
        jTextField1.setVisible(false);
        ConsultCourseOperationItems.jLabel4DeleteItem.setVisible(true);
        ConsultCourseOperationItems.jLabel4AddItem.setVisible(false);
        ConsultCourseOperationItems.jLabel5ModifyItem.setVisible(false);
        jButton4ApplyAddItem.setVisible(false);
        jButton4ApplyModifyItem.setVisible(false);
        jButton4ApplyDeleteItem.setVisible(true);
        
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        jButton4.setVisible(false);
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        jTextField1.setVisible(false);
        ConsultCourseOperationItems.jLabel5ModifyItem.setVisible(true);
        ConsultCourseOperationItems.jLabel4AddItem.setVisible(false);
        ConsultCourseOperationItems.jLabel4DeleteItem.setVisible(false);
        jButton4ApplyAddItem.setVisible(false);
        jButton4ApplyDeleteItem.setVisible(false);
        jButton4ApplyModifyItem.setVisible(true);
        
       jTabbedPane1.setSelectedIndex(1);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ApplyAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ApplyAddItemActionPerformed
        
        jButton4ApplyDeleteItem.setVisible(false);
        jButton4ApplyModifyItem.setVisible(false);
        
        DefaultTableModel modelo = new DefaultTableModel();

            PreparedStatement ps = null;
            try{
                Conexion objCon = new Conexion();
                Connection conn = objCon.getConection();
                ps = conn.prepareStatement("INSERT INTO `practicedb`.`course` (`CourseCode`, `Section`, `Title`, `Professor`) VALUES (?, ?, ?, ?);");
                ps.setString(1, jTextField1CourseCode.getText());
                ps.setString(2, jTextField2Section.getText());
                ps.setString(3, jTextField3Title.getText());
                ps.setString(4, jTextField8Professor.getText());
                
                ps.execute();
                
                JOptionPane.showMessageDialog(null, "Item added succesfully");
                Object[] fila = new Object[4];
                fila[0] = jTextField1CourseCode.getText();
                fila[1] = jTextField2Section.getText();
                fila[2] = jTextField3Title.getText();
                fila[3] = jTextField8Professor.getText();
                modelo.addRow(fila);
            }   catch (SQLException ex) {
                Logger.getLogger(InterfaceFinalProjectDB.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_jButton4ApplyAddItemActionPerformed

    private void jButton4ApplyDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ApplyDeleteItemActionPerformed
        
        
        jButton4ApplyAddItem.setVisible(false);
        jButton4ApplyModifyItem.setVisible(false);
                DefaultTableModel modelo = new DefaultTableModel();

            PreparedStatement ps = null;
            try{
                Conexion objCon = new Conexion();
                Connection conn = objCon.getConection();
                ps = conn.prepareStatement("DELETE FROM `practicedb`.`room` WHERE (`RoomId` = ?);");
                ps.setString(1, jTextField1CourseCode.getText());
                
                
                ps.execute();
                
                JOptionPane.showMessageDialog(null, "Item deleted succesfully");
                Object[] fila = new Object[1];
                fila[0] = jTextField1CourseCode.getText();
                
                modelo.addRow(fila);
            }   catch (SQLException ex) {
                Logger.getLogger(InterfaceFinalProjectDB.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_jButton4ApplyDeleteItemActionPerformed

    private void jButton4ApplyModifyItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ApplyModifyItemActionPerformed
        
              
       DefaultTableModel modelo = new DefaultTableModel();
       
       String CourseCodeText = jTextField5ModifyCourseCodeDone.getText();
       String SectionText = jTextField6ModifySectionDone.getText();
       String TitleText = jTextField7ModifyTitleDone.getText();
       String ProfessorText =jTextField9ModifyProfessorDone.getText();
       
            PreparedStatement ps = null;
            try{
                Conexion objCon = new Conexion();
                Connection conn = objCon.getConection();
                ps = conn.prepareStatement("UPDATE `practicedb`.`course` SET `CourseCode` = '"+CourseCodeText+"', `Section` = '"+SectionText+"', `Title` = '"+TitleText+
                                            "', `Professor` = '"+ProfessorText+"' WHERE (`CourseCode` = ?) and (`Section` = ?);");
                ps.setString(1, jTextField2ModifyCourseCode.getText());
                ps.setString(2, jTextField3ModifySection.getText());
                
                
                ps.execute();
                
                JOptionPane.showMessageDialog(null, "Item modified succesfully");
                Object[] fila = new Object[4];
                fila[0] = jTextField5ModifyCourseCodeDone.getText();
                fila[1] = jTextField6ModifySectionDone.getText();
                fila[2] = jTextField7ModifyTitleDone.getText();
                fila[3] = jTextField9ModifyProfessorDone.getText();
                modelo.addRow(fila);
            }   catch (SQLException ex) {
                Logger.getLogger(InterfaceFinalProjectDB.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton4ApplyModifyItemActionPerformed

    private void jButton5CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5CancelActionPerformed
        try {
            Conexion.getConection().rollback();
        } catch (SQLException ex) {
            Logger.getLogger(ConsultCourseOperationItems.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5CancelActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     
          
       int confirmado = JOptionPane.showConfirmDialog(null,
                        "Are you sure you want drop this table?");

    if (JOptionPane.OK_OPTION == confirmado){
        System.out.println("Table dropped");
        
         DefaultTableModel modelo = new DefaultTableModel();
            PreparedStatement ps = null;
            try{
                Conexion objCon = new Conexion();
                Connection conn = objCon.getConection();
                ps = conn.prepareStatement("DROP TABLE Course;");
                ps.setString(1, jTextField2ModifyCourseCode.getText());
                
                
                ps.execute();
                
                JOptionPane.showMessageDialog(null, "Table dropped");
                Object[] fila = new Object[3];
                fila[0] = null;
                fila[1] = null;
                fila[2] = null;
                modelo.addRow(fila);
            }   catch (SQLException ex) {
                Logger.getLogger(InterfaceFinalProjectDB.class.getName()).log(Level.SEVERE, null, ex);
            }
            
    }else{
            System.out.println("No table dropped");
    }
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField2SectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2SectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2SectionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultCourseOperationItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultCourseOperationItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultCourseOperationItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultCourseOperationItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultCourseOperationItems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public static javax.swing.JButton jButton4;
    private javax.swing.JButton jButton4ApplyAddItem;
    public static javax.swing.JButton jButton4ApplyDeleteItem;
    public static javax.swing.JButton jButton4ApplyModifyItem;
    private javax.swing.JButton jButton5Cancel;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel13Professor;
    private javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel4AddItem;
    public static javax.swing.JLabel jLabel4DeleteItem;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel5ModifyItem;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField1CourseCode;
    private javax.swing.JTextField jTextField2ModifyCourseCode;
    private javax.swing.JTextField jTextField2Section;
    private javax.swing.JTextField jTextField3ModifySection;
    private javax.swing.JTextField jTextField3Title;
    private javax.swing.JTextField jTextField4ModifyTitle;
    private javax.swing.JTextField jTextField5ModifyCourseCodeDone;
    private javax.swing.JTextField jTextField6ModifySectionDone;
    private javax.swing.JTextField jTextField7ModifyTitleDone;
    private javax.swing.JTextField jTextField8ModifyProfessor;
    public static javax.swing.JTextField jTextField8Professor;
    private javax.swing.JTextField jTextField9ModifyProfessorDone;
    // End of variables declaration//GEN-END:variables
}
